name = "dcspark/vault"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for the Projected NFT Whirlpool"

[repository]
user = "dcspark"
project = "vault"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "add-value-to-list"
source = "github"
